import { Product, Category, CarouselSlide, Promotion } from '../types';

export const categories: Category[] = [
  { id: 1, name: '服装鞋帽', icon: '👔', productCount: 2580 },
  { id: 2, name: '电子产品', icon: '📱', productCount: 1890 },
  { id: 3, name: '家居生活', icon: '🏠', productCount: 1450 },
  { id: 4, name: '美妆护肤', icon: '💄', productCount: 980 },
  { id: 5, name: '运动户外', icon: '⚽', productCount: 860 },
  { id: 6, name: '食品生鲜', icon: '🍎', productCount: 1230 },
  { id: 7, name: '母婴用品', icon: '👶', productCount: 670 },
  { id: 8, name: '图书文具', icon: '📚', productCount: 540 },
];

export const allProducts: Product[] = [
  // 服装鞋帽
  {
    id: 1,
    name: '时尚运动鞋',
    price: 299,
    originalPrice: 399,
    rating: 4.8,
    reviews: 234,
    category: '服装鞋帽',
  },
  {
    id: 2,
    name: '简约双肩包',
    price: 199,
    originalPrice: 259,
    rating: 4.9,
    reviews: 156,
    category: '服装鞋帽',
  },
  {
    id: 3,
    name: '休闲卫衣',
    price: 159,
    originalPrice: 199,
    rating: 4.7,
    reviews: 89,
    category: '服装鞋帽',
  },
  {
    id: 4,
    name: '商务衬衫',
    price: 129,
    originalPrice: 169,
    rating: 4.6,
    reviews: 67,
    category: '服装鞋帽',
  },
  // 电子产品
  {
    id: 5,
    name: '无线蓝牙耳机',
    price: 159,
    originalPrice: 199,
    rating: 4.6,
    reviews: 189,
    category: '电子产品',
  },
  {
    id: 6,
    name: '智能手表',
    price: 899,
    originalPrice: 1099,
    rating: 4.7,
    reviews: 98,
    category: '电子产品',
  },
  {
    id: 7,
    name: '便携充电宝',
    price: 89,
    originalPrice: 129,
    rating: 4.5,
    reviews: 234,
    category: '电子产品',
  },
  {
    id: 8,
    name: '手机支架',
    price: 49,
    originalPrice: 69,
    rating: 4.4,
    reviews: 56,
    category: '电子产品',
  },
  // 家居生活
  {
    id: 9,
    name: '简约台灯',
    price: 129,
    originalPrice: 179,
    rating: 4.8,
    reviews: 145,
    category: '家居生活',
  },
  {
    id: 10,
    name: '收纳箱套装',
    price: 79,
    originalPrice: 99,
    rating: 4.7,
    reviews: 78,
    category: '家居生活',
  },
  {
    id: 11,
    name: '加厚地毯',
    price: 199,
    originalPrice: 259,
    rating: 4.6,
    reviews: 92,
    category: '家居生活',
  },
  {
    id: 12,
    name: '保温杯',
    price: 69,
    originalPrice: 89,
    rating: 4.9,
    reviews: 167,
    category: '家居生活',
  },
  // 美妆护肤
  {
    id: 13,
    name: '护肤套装',
    price: 299,
    originalPrice: 399,
    rating: 4.9,
    reviews: 201,
    category: '美妆护肤',
  },
  {
    id: 14,
    name: '时尚太阳镜',
    price: 129,
    originalPrice: 179,
    rating: 4.5,
    reviews: 87,
    category: '美妆护肤',
  },
  {
    id: 15,
    name: '口红套装',
    price: 199,
    originalPrice: 259,
    rating: 4.8,
    reviews: 134,
    category: '美妆护肤',
  },
  {
    id: 16,
    name: '化妆刷套装',
    price: 89,
    originalPrice: 119,
    rating: 4.6,
    reviews: 98,
    category: '美妆护肤',
  },
  // 运动户外
  {
    id: 17,
    name: '运动健身套装',
    price: 159,
    originalPrice: 199,
    rating: 4.8,
    reviews: 145,
    category: '运动户外',
  },
  {
    id: 18,
    name: '瑜伽垫',
    price: 79,
    originalPrice: 99,
    rating: 4.7,
    reviews: 112,
    category: '运动户外',
  },
  {
    id: 19,
    name: '运动水壶',
    price: 49,
    originalPrice: 69,
    rating: 4.5,
    reviews: 78,
    category: '运动户外',
  },
  {
    id: 20,
    name: '跳绳',
    price: 29,
    originalPrice: 39,
    rating: 4.4,
    reviews: 56,
    category: '运动户外',
  },
  // 食品生鲜
  {
    id: 21,
    name: '有机零食礼盒',
    price: 89,
    originalPrice: 129,
    rating: 4.6,
    reviews: 112,
    category: '食品生鲜',
  },
  {
    id: 22,
    name: '进口水果组合',
    price: 129,
    originalPrice: 169,
    rating: 4.7,
    reviews: 89,
    category: '食品生鲜',
  },
  {
    id: 23,
    name: '坚果礼盒',
    price: 159,
    originalPrice: 199,
    rating: 4.8,
    reviews: 145,
    category: '食品生鲜',
  },
  {
    id: 24,
    name: '有机茶叶',
    price: 199,
    originalPrice: 259,
    rating: 4.9,
    reviews: 167,
    category: '食品生鲜',
  },
  // 母婴用品
  {
    id: 25,
    name: '婴儿纸尿裤',
    price: 89,
    originalPrice: 119,
    rating: 4.8,
    reviews: 234,
    category: '母婴用品',
  },
  {
    id: 26,
    name: '儿童玩具套装',
    price: 129,
    originalPrice: 169,
    rating: 4.7,
    reviews: 89,
    category: '母婴用品',
  },
  {
    id: 27,
    name: '婴儿安抚奶嘴',
    price: 29,
    originalPrice: 39,
    rating: 4.6,
    reviews: 156,
    category: '母婴用品',
  },
  {
    id: 28,
    name: '儿童安全座椅',
    brand: '宝贝天使',
    price: 599,
    originalPrice: 799,
    rating: 4.9,
    reviews: 78,
    category: '母婴用品',
  },
  // 图书文具
  {
    id: 29,
    name: '畅销书套装',
    brand: '新华书店',
    price: 199,
    originalPrice: 259,
    rating: 4.8,
    reviews: 112,
    category: '图书文具',
  },
  {
    id: 30,
    name: '文具礼盒',
    brand: '得力办公',
    price: 89,
    originalPrice: 119,
    rating: 4.7,
    reviews: 67,
    category: '图书文具',
  },
];

export const carouselSlides: CarouselSlide[] = [
  {
    id: 1,
    title: '夏季新品上市',
    subtitle: '全场满299减50',
    image: '',
    cta: '立即抢购',
    link: '/products',
  },
  {
    id: 2,
    title: '智能生活节',
    subtitle: '电子产品限时特惠',
    image: '',
    cta: '探索更多',
    link: '/products',
  },
  {
    id: 3,
    title: '会员专享',
    subtitle: '注册即享100元优惠券',
    image: '',
    cta: '免费注册',
    link: '/cart',
  },
  {
    id: 4,
    title: '品质好物',
    subtitle: '精选大牌低至5折',
    image: '',
    cta: '马上购买',
    link: '/products',
  },
];

export const promotions: Promotion[] = [
  {
    id: 1,
    title: '限时闪购',
    description: '精选商品低至3折',
    discount: '70% OFF',
    validUntil: '2026-03-31',
    image: '',
  },
  {
    id: 2,
    title: '新用户专享',
    description: '首单立减30元',
    discount: '¥30',
    validUntil: '2026-04-15',
    image: '',
  },
  {
    id: 3,
    title: '品牌特卖',
    description: '大牌折扣季',
    discount: '50% OFF',
    validUntil: '2026-04-01',
    image: '',
  },
  {
    id: 4,
    title: '满减活动',
    description: '满499减100',
    discount: '¥100',
    validUntil: '2026-03-30',
    image: '',
  },
  {
    id: 5,
    title: '会员日特惠',
    description: '会员专享8折',
    discount: '20% OFF',
    validUntil: '2026-04-10',
    image: '',
  },
  {
    id: 6,
    title: '清仓甩卖',
    description: '部分商品2折起',
    discount: '80% OFF',
    validUntil: '2026-04-05',
    image: '',
  },
];

export const productsByCategory = (categoryName: string): Product[] => {
  return allProducts.filter(p => p.category === categoryName);
};
