name = "glowup-beauty"
compatibility_date = "2026-04-18"

[build]
command = "npm run build"
upload_directory = "dist"

[build.environment]
NODE_VERSION = "20"

pages_build_output_dir = "dist"